### PR TITLE
Updated Signup-dates

### PR DESCRIPTION
**Pull request by IsabellaHoesch**
## Description
Decided to prolong the signup period by 2 weeks.
Updated the dates in the config file so that the webapp shows the new correct dates to interested visitors.

## Note:
Need to discuss - will this affect how entries are stored in db?

### CODE REVIEW

**Comment by rycmak** [comment]
Before pushing this change, we should update the dates in the `rounds` table first, so that everyone signing up during the extended period would have the same `round_id` as those who have already signed up.

**Comment by IsabellaHoesch** [comment]
Good point! I updated it just now!

**Comment by rycmak** [comment]
One slight change: the end date in the config file is 2021-09-27, but the end date in `rounds` table is 2021-09-26 -- this will cause the DB to try to create a new record in the `rounds` table, which will fail because the unique pair (`year`, `round_num`) = (`2021`, `3`) already exists.

**Comment by IsabellaHoesch** [comment]
Thanks for seeing that! I updated the config file so that end dates match (September 26)

**Comment by rycmak** [comment]
One more thing I missed: `round_num` should be 3 for current round, not 1.

**Pull request merged**
